# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f2649c9ac2fb0e331027c8be5eb67d9a3dbaf235288cd3546acb4520a566a5a5c2be72243b5d944148fbcaf772dd4a751fd1416206c234a92e2e4a6c9e0acda6

test:
  secret_key_base: ca89952b82be23def77e2f3c7b962cb06625707531b99e27aa04d4565e710038de3e4516dbf2b9c448803971ee395ba8473051efc0caf8e223facefe0b06d952

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
